channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python==3.6.9
  - pandas==0.25.0
  - rpy2
  - r-base
  - java-jdk=8
  - pyspark
  - r-seurat==3.0.2
  - rstudio
  - r-irkernel
  - pip
  - pip:
    - matplotlib
    - seaborn
    - pandas
    - sklearn
    - numpy
